### ISSUE TITLE
Court District Shapefiles

### ISSUE THREAD

**Issue by RossThorn** [RossThorn/human-trafficking-viz#3]
Find information/shapefiles on court districts for map.
Federal (found)
State

**Comment by AliciaAIverson** [comment]
I found a shapefile for State Judicial districts based on a US counties layer; Editing in qGIS. 

Source: https://gis.stackexchange.com/questions/3533/gis-layer-of-usa-state-court-jurisdiction-boundaries OR https://onedrive.live.com/?id=C754C68262A316DC%21109&cid=C754C68262A316DC (Brad Nesom 2010)
