### ISSUE TITLE
Check Boxes Not Resetting on upwards scroll

### ISSUE THREAD

**Issue by LeanneAbraham** [RossThorn/human-trafficking-viz#74]

**Comment by RossThorn** [comment]
So when I do it on my computer I don't have any problems. The boxes remain checked but it adds the correct json (with the filters already applied). So I don't know what the problem was. But I wrote code so that it unchecks the boxes when the court districts json is not on the map.

**Comment by LeanneAbraham** [comment]
Added in a button to reset all the checkboxes on exploration. That seems like a simple fix. The boxes were not unchecking when the json was not on the map for me.
